$proxy = Get-ItemProperty "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings"
Write-Output "ProxyEnable: $($proxy.ProxyEnable)"
Write-Output "ProxyServer: $($proxy.ProxyServer)"
Write-Output "--- User env proxies ---"
Write-Output "HTTP_PROXY(User): $([Environment]::GetEnvironmentVariable('HTTP_PROXY','User'))"
Write-Output "HTTPS_PROXY(User): $([Environment]::GetEnvironmentVariable('HTTPS_PROXY','User'))"
Write-Output "http_proxy(User): $([Environment]::GetEnvironmentVariable('http_proxy','User'))"
Write-Output "https_proxy(User): $([Environment]::GetEnvironmentVariable('https_proxy','User'))"
Write-Output "--- Machine env proxies ---"
Write-Output "HTTP_PROXY(Machine): $([Environment]::GetEnvironmentVariable('HTTP_PROXY','Machine'))"
Write-Output "HTTPS_PROXY(Machine): $([Environment]::GetEnvironmentVariable('HTTPS_PROXY','Machine'))"
Write-Output "--- Current session env proxies ---"
Write-Output "HTTP_PROXY: $env:HTTP_PROXY"
Write-Output "HTTPS_PROXY: $env:HTTPS_PROXY"
